services:
  db23:
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_PDB=${ORACLE_PDB} # I'm using a .ENV file for these two values, but you can specify directly in the compose file.
      - ORACLE_PWD=${ORACLE_PWD}
    ports:
      - "1521:1521"
    networks:
      - appnet

  ords-node:
    image: container-registry.oracle.com/database/ords:latest
    platform: linux/amd64
    environment:
      - DBSERVICENAME=${ORACLE_PDB} # I'm using a .ENV file for these next three values, but you can specify directly in the compose file.
      - DBHOST=db23
      - DBPORT=${DBPORT}
      - ORACLE_PWD=${ORACLE_PWD}
      # - APEX_PWD=${ORACLE_PWD} # You can specify a password, otherwise we will generate one for you.
    volumes:
      - ./apex-latest/apex:/opt/oracle/apex   # This mapping is what triggers the APEX installation. We'll update the README to make this more clear.
                                              # I've downloaded the latest APEX build in a directory called apex-latest, inside is 
                                              # another directory called /apex/
                                              # The Entrypoint.sh looks for this mapped volume and then if present, kicks off the
                                              # APEX install.
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --noproxy "localhost" -f -k http://localhost:8080/ords/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 150
    depends_on:    
      db23:
        condition: service_healthy 
    networks:
      - appnet
networks:
  appnet:
    driver: bridge