-- GRANT statements for HR schema
GRANT ALL PRIVILEGES ON hr.regions TO PUBLIC;
GRANT ALL PRIVILEGES ON hr.countries TO PUBLIC;
GRANT ALL PRIVILEGES ON hr.locations TO PUBLIC;
GRANT ALL PRIVILEGES ON hr.departments TO PUBLIC;
GRANT ALL PRIVILEGES ON hr.jobs TO PUBLIC;
GRANT ALL PRIVILEGES ON hr.employees TO PUBLIC;
GRANT ALL PRIVILEGES ON hr.job_history TO PUBLIC;
GRANT ALL PRIVILEGES ON hr.emp_details_view TO PUBLIC;
GRANT EXECUTE ON hr.secure_dml TO PUBLIC;
GRANT EXECUTE ON hr.add_job_history TO PUBLIC;

-- GRANT statements for CO schema
GRANT ALL PRIVILEGES ON co.customers TO PUBLIC;
GRANT ALL PRIVILEGES ON co.stores TO PUBLIC;
GRANT ALL PRIVILEGES ON co.products TO PUBLIC;
GRANT ALL PRIVILEGES ON co.orders TO PUBLIC;
GRANT ALL PRIVILEGES ON co.shipments TO PUBLIC;
GRANT ALL PRIVILEGES ON co.order_items TO PUBLIC;
GRANT ALL PRIVILEGES ON co.inventory TO PUBLIC;
GRANT ALL PRIVILEGES ON co.customer_order_products TO PUBLIC;
GRANT ALL PRIVILEGES ON co.store_orders TO PUBLIC;
GRANT ALL PRIVILEGES ON co.product_reviews TO PUBLIC;
GRANT ALL PRIVILEGES ON co.product_orders TO PUBLIC;

-- GRANT statements for SH schema
GRANT ALL PRIVILEGES ON sh.countries TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.customers TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.promotions TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.products TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.times TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.channels TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.sales TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.costs TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.supplementary_demographics TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.profits TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.cal_month_sales_mv TO PUBLIC;
GRANT ALL PRIVILEGES ON sh.fweek_pscat_sales_mv TO PUBLIC;
