-- ================================
-- DROP OBJECTS IF EXISTS
-- ================================
DROP VIEW v_emp_dept_summary;
DROP JSON RELATIONAL DUALITY VIEW dept_projects_dv;
DROP FUNCTION fn_longest_tenured_employee;
DROP PROCEDURE pr_add_and_assign_employee;
DROP TABLE employee CASCADE CONSTRAINTS;
DROP TABLE project CASCADE CONSTRAINTS;
DROP TABLE department CASCADE CONSTRAINTS;

-- ================================
-- CREATE TABLES
-- ================================
CREATE TABLE department (
  dept_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  dept_code   CHAR(5) NOT NULL,
  established DATE,
  details     JSON
);

CREATE TABLE project (
  proj_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  proj_name  VARCHAR2(100) NOT NULL,
  dept_id    NUMBER NOT NULL,
  is_active  BOOLEAN
);

CREATE TABLE employee (
  emp_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  emp_name   VARCHAR2(100) NOT NULL,
  dept_id    NUMBER NOT NULL,
  comments   CLOB
);

-- ================================
-- ADD CONSTRAINTS
-- ================================
ALTER TABLE project ADD CONSTRAINT fk_project_dept
FOREIGN KEY (dept_id) REFERENCES department (dept_id);

ALTER TABLE employee ADD CONSTRAINT fk_employee_dept
FOREIGN KEY (dept_id) REFERENCES department (dept_id);

-- ================================
-- INSERT SAMPLE DATA
-- ================================
INSERT INTO department (dept_code, established, details) VALUES
  ('HR001', DATE '2001-04-13', JSON_OBJECT('location' VALUE 'Bldg 1', 'members' VALUE 25)),
  ('FN002', DATE '2002-06-20', JSON_OBJECT('location' VALUE 'Bldg 2', 'members' VALUE 20)),
  ('EN003', DATE '2000-11-01', JSON_OBJECT('location' VALUE 'Bldg 3', 'members' VALUE 40)),
  ('SA004', DATE '2005-01-15', JSON_OBJECT('location' VALUE 'Bldg 4', 'members' VALUE 18)),
  ('MK005', DATE '2003-12-07', JSON_OBJECT('location' VALUE 'Bldg 5', 'members' VALUE 15)),
  ('LG006', DATE '2010-03-31', JSON_OBJECT('location' VALUE 'Bldg 6', 'members' VALUE 5)),
  ('IT007', DATE '2001-09-23', JSON_OBJECT('location' VALUE 'Bldg 7', 'members' VALUE 30)),
  ('SP008', DATE '2015-05-05', JSON_OBJECT('location' VALUE 'Bldg 8', 'members' VALUE 12)),
  ('LG009', DATE '2012-07-14', JSON_OBJECT('location' VALUE 'Bldg 9', 'members' VALUE 10)),
  ('OP010', DATE '2008-08-01', JSON_OBJECT('location' VALUE 'Bldg 10', 'members' VALUE 22));

INSERT INTO project (proj_name, dept_id, is_active) VALUES
  ('Onboarding', 1, TRUE),
  ('Audit2024', 2, FALSE),
  ('NewApp', 3, TRUE),
  ('SalesCampaign', 4, TRUE),
  ('SocialMediaPush', 5, FALSE),
  ('Compliance', 6, TRUE),
  ('UpgradeInfra', 7, TRUE),
  ('HelpdeskRevamp', 8, TRUE),
  ('FleetUpdate', 9, TRUE),
  ('ProcessReorg', 10, FALSE);

INSERT INTO employee (emp_name, dept_id, comments) VALUES
  ('Alice', 1,  'Strong analyst, quick learner.'),
  ('Bob', 2,  'CPA certification in progress.'),
  ('Carol', 3,  'Dev team lead for NewApp project.'),
  ('David', 4,  'Consistent sales over target.'),
  ('Eve', 5,  'Leads digital campaigns.'),
  ('Frank', 6,  'Subject matter expert in compliance.'),
  ('Grace', 7,  'Skilled in infrastructure upgrades.'),
  ('Heidi', 8,  'Customer support supervisor.'),
  ('Ivan', 9,  'Fleet manager - long tenure.'),
  ('Judy', 10,  'Operations management veteran.');

-- ================================
-- 1. STANDARD VIEW
-- ================================
CREATE OR REPLACE VIEW v_emp_dept_summary AS
SELECT
  e.emp_id,
  e.emp_name,
  d.dept_code,
  TO_CHAR(d.established, 'YYYY-MM-DD') AS established,
  d.details,
  e.comments
FROM
  employee e
  JOIN department d ON e.dept_id = d.dept_id;

-- ================================
-- 2. JSON-RELATIONAL DUALITY VIEW
-- ================================
CREATE JSON RELATIONAL DUALITY VIEW dept_projects_dv AS
SELECT JSON
{
  '_id'        : d.dept_id,
  'dept_code'  : d.dept_code,
  'established': d.established,
  'details'    : d.details,
  'projects'   : [
    SELECT JSON {
      'proj_id': p.proj_id,
      'proj_name': p.proj_name,
      'is_active': p.is_active
    }
    FROM project p WHERE p.dept_id = d.dept_id
  ]
}
FROM department d;
/

-- ================================
-- 3. COMPLEX SQL QUERY
--    (for employee counts, department with max active projects, projects per dept)
-- ================================
SELECT
  d.dept_id,
  d.dept_code,
  COUNT(DISTINCT e.emp_id) AS emp_count,
  COUNT(DISTINCT p.proj_id) AS project_count,
  SUM(CASE WHEN p.is_active = TRUE THEN 1 ELSE 0 END) AS active_proj_count
FROM
  department d
  LEFT JOIN project p ON d.dept_id = p.dept_id
  LEFT JOIN employee e ON d.dept_id = e.dept_id
GROUP BY d.dept_id, d.dept_code
HAVING SUM(CASE WHEN p.is_active = TRUE THEN 1 ELSE 0 END) = (
    SELECT MAX(cnt) FROM
      (SELECT COUNT(*) AS cnt FROM project WHERE is_active = TRUE GROUP BY dept_id)
  )
ORDER BY emp_count DESC;

-- ================================
-- 4. PL/SQL PROCEDURE (add employee, assign to dept)
-- ================================
CREATE OR REPLACE PROCEDURE pr_add_and_assign_employee(
  p_emp_name IN VARCHAR2,
  p_dept_code IN CHAR,
  p_comments IN CLOB
) AS
  v_dept_id NUMBER;
BEGIN
  -- Find department ID
  SELECT dept_id INTO v_dept_id
    FROM department
    WHERE dept_code = p_dept_code;

  -- Insert employee
  INSERT INTO employee (emp_name, dept_id, comments)
    VALUES (p_emp_name, v_dept_id, p_comments);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.put_line('Department code not found.');
END;
/
-- Example call:
-- EXEC pr_add_and_assign_employee('Kim', 'HR001', 'New HR assistant.');

-- ================================
-- 5. PL/SQL FUNCTION (find name of longest comment)
-- ================================
CREATE OR REPLACE FUNCTION fn_longest_tenured_employee RETURN VARCHAR2 IS
  v_name VARCHAR2(100);
BEGIN
  SELECT emp_name INTO v_name
    FROM employee
    WHERE LENGTH(comments) = (
      SELECT MAX(LENGTH(comments)) FROM employee
    )
    FETCH FIRST ROW ONLY;
  RETURN v_name;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;
END;
/
-- Example call:
-- SELECT fn_longest_tenured_employee FROM dual;
