FROM container-registry.oracle.com/os/oraclelinux:9

ARG USER_HOME_DIR="/root"

ENV ORACLE_BASE=/opt/oracle \
    JDK_RPM="jdk.rpm" \
    SQLCL_RPM="sqlcl.rpm"

COPY ncurses.rpm /tmp/ncurses.rpm
COPY "${JDK_RPM}" /tmp/"${JDK_RPM}"
COPY "${SQLCL_RPM}" /tmp/"${SQLCL_RPM}"

VOLUME [ "/opt/oracle/sql_scripts" ]

RUN rpm -i /tmp/"${JDK_RPM}"  && \
    rpm -i /tmp/"${SQLCL_RPM}" && \
    rpm -i --nodeps /tmp/ncurses.rpm && \
    echo "export PATH=/opt/oracle/sqlcl/bin:$PATH" > /etc/profile.d/sqlcl.sh  && \
    rm /tmp/"${JDK_RPM}" /tmp/"${SQLCL_RPM}"

ENV PATH="${PATH}:$ORACLE_BASE/sqlcl/bin"

WORKDIR /opt/oracle/sql_scripts
ENTRYPOINT  ["/opt/oracle/sqlcl/bin/sql"],
CMD [ "/nolog" ]

