-- ==========================================
-- DROP TABLES (in dependency order, ignore if not exist)
-- ==========================================
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PROJECT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ==========================================
-- CREATE TABLES
-- ==========================================
CREATE TABLE DEPARTMENT (
  DEPT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DEPT_CODE CHAR(5) NOT NULL,
  ESTABLISHED DATE,
  DETAILS JSON
);

CREATE TABLE EMPLOYEE (
  EMP_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  EMP_NAME VARCHAR2(100) NOT NULL,
  DEPT_ID NUMBER NOT NULL,
  COMMENTS CLOB,
  CONSTRAINT FK_EMPLOYEE_DEPT FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT (DEPT_ID)
);

CREATE TABLE PROJECT (
  PROJ_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PROJ_NAME VARCHAR2(100) NOT NULL,
  DEPT_ID NUMBER NOT NULL,
  IS_ACTIVE BOOLEAN,
  CONSTRAINT FK_PROJECT_DEPT FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT (DEPT_ID)
);

-- ==========================================
-- INSERT DATA
-- ==========================================
INSERT INTO DEPARTMENT (DEPT_CODE, ESTABLISHED, DETAILS) VALUES
  ('HR001', DATE '2001-04-13', JSON_OBJECT('location' VALUE 'Bldg 1', 'members' VALUE 25)),
  ('FN002', DATE '2002-06-20', JSON_OBJECT('location' VALUE 'Bldg 2', 'members' VALUE 20)),
  ('EN003', DATE '2000-11-01', JSON_OBJECT('location' VALUE 'Bldg 3', 'members' VALUE 40)),
  ('SA004', DATE '2005-01-15', JSON_OBJECT('location' VALUE 'Bldg 4', 'members' VALUE 18)),
  ('MK005', DATE '2003-12-07', JSON_OBJECT('location' VALUE 'Bldg 5', 'members' VALUE 15)),
  ('LG006', DATE '2010-03-31', JSON_OBJECT('location' VALUE 'Bldg 6', 'members' VALUE 5)),
  ('IT007', DATE '2001-09-23', JSON_OBJECT('location' VALUE 'Bldg 7', 'members' VALUE 30)),
  ('SP008', DATE '2015-05-05', JSON_OBJECT('location' VALUE 'Bldg 8', 'members' VALUE 12)),
  ('LG009', DATE '2012-07-14', JSON_OBJECT('location' VALUE 'Bldg 9', 'members' VALUE 10)),
  ('OP010', DATE '2008-08-01', JSON_OBJECT('location' VALUE 'Bldg 10', 'members' VALUE 22));

INSERT INTO PROJECT (PROJ_NAME, DEPT_ID, IS_ACTIVE) VALUES
  ('Onboarding', 1, TRUE),
  ('Audit2024', 2, FALSE),
  ('NewApp', 3, TRUE),
  ('SalesCampaign', 4, TRUE),
  ('SocialMediaPush', 5, FALSE),
  ('Compliance', 6, TRUE),
  ('UpgradeInfra', 7, TRUE),
  ('HelpdeskRevamp', 8, TRUE),
  ('FleetUpdate', 9, TRUE),
  ('ProcessReorg', 10, FALSE);

INSERT INTO EMPLOYEE (EMP_NAME, DEPT_ID, COMMENTS) VALUES
  ('Alice', 1,  'Strong analyst, quick learner.'),
  ('Bob', 2,  'CPA certification in progress.'),
  ('Carol', 3,  'Dev team lead for NewApp project.'),
  ('David', 4,  'Consistent sales over target.'),
  ('Eve', 5,  'Leads digital campaigns.'),
  ('Frank', 6,  'Subject matter expert in compliance.'),
  ('Grace', 7,  'Skilled in infrastructure upgrades.'),
  ('Heidi', 8,  'Customer support supervisor.'),
  ('Ivan', 9,  'Fleet manager - long tenure.'),
  ('Judy', 10,  'Operations management veteran.');

-- ==========================================
-- FUNCTION: FN_LONGEST_TENURED_EMPLOYEE
-- ==========================================
CREATE OR REPLACE FUNCTION FN_LONGEST_TENURED_EMPLOYEE RETURN VARCHAR2 IS
  v_name VARCHAR2(100);
BEGIN
  SELECT emp_name INTO v_name
  FROM EMPLOYEE
  WHERE LENGTH(comments) = (
    SELECT MAX(LENGTH(comments)) FROM EMPLOYEE
  )
  FETCH FIRST ROW ONLY;
  RETURN v_name;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN NULL;
END;
/

-- ==========================================
-- PROCEDURE: PR_ADD_AND_ASSIGN_EMPLOYEE
-- ==========================================
CREATE OR REPLACE PROCEDURE PR_ADD_AND_ASSIGN_EMPLOYEE (
  p_emp_name IN VARCHAR2,
  p_dept_code IN CHAR,
  p_comments IN CLOB
) AS
  v_dept_id NUMBER;
BEGIN
  SELECT dept_id INTO v_dept_id
  FROM DEPARTMENT
  WHERE dept_code = p_dept_code;

  INSERT INTO EMPLOYEE (emp_name, dept_id, comments)
  VALUES (p_emp_name, v_dept_id, p_comments);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.put_line('Department code not found.');
END;
/

-- ==========================================
-- JSON-RELATIONAL DUALITY VIEW: DEPT_PROJECTS_DV
-- ==========================================
CREATE OR REPLACE FORCE EDITIONABLE JSON RELATIONAL DUALITY VIEW DEPT_PROJECTS_DV AS
SELECT JSON
{
  '_id'        : d.dept_id,
  'dept_code'  : d.dept_code,
  'established': d.established,
  'details'    : d.details,
  'projects'   : [
    SELECT JSON {
      'proj_id': p.proj_id,
      'proj_name': p.proj_name,
      'is_active': p.is_active
    }
    FROM PROJECT p WITH INSERT UPDATE DELETE
    WHERE p.dept_id = d.dept_id
  ]
}
FROM DEPARTMENT d WITH INSERT UPDATE DELETE;
/

-- ==========================================
-- VIEW: V_EMP_DEPT_SUMMARY
-- ==========================================
CREATE OR REPLACE VIEW V_EMP_DEPT_SUMMARY (
  EMP_ID, EMP_NAME, DEPT_CODE, ESTABLISHED, DETAILS, COMMENTS
) AS
SELECT
  e.emp_id,
  e.emp_name,
  d.dept_code,
  TO_CHAR(d.established, 'YYYY-MM-DD') AS established,
  d.details,
  e.comments
FROM
  EMPLOYEE e
  JOIN DEPARTMENT d ON e.dept_id = d.dept_id;

COMMIT;


